version: "3.5"
services:
  db2:
    image: "mongo:4.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - "./db/data/db-files:/data/db"
    ports:
      - 27017:27017
    networks:
      - tis_net
networks:
  tis_net:
    external: true
